### ISSUE TITLE
Improve Button Positioning

### ISSUE THREAD

**Issue by juanpisss** [juanpisss/LARD#1]
```css
button {
  position: relative;
  top: -450px;
  /* this can be done WAYYY better */
  /* but i have this due by tomorrow */
  /* reference: issue #1 */
}
```

https://github.com/juanpisss/LARD/blob/fe1b1f091dab5a0d704e3e5a133269a703aa8bac/client/src/SearchBar.css#L44
